ALTER TABLE catastro_v2.pgmetadata.dataset
ADD COLUMN db_name TEXT,
ADD COLUMN username TEXT,
ADD COLUMN purpose TEXT,
ADD COLUMN md_dataidentification_language TEXT,
ADD COLUMN topiccategory TEXT[],
ADD COLUMN groupcategory TEXT,
ADD COLUMN presentationform TEXT[],
ADD COLUMN ci_onlineresource_linkage TEXT,
ADD COLUMN ci_onlineresource_description TEXT,
ADD COLUMN maintenanceandupdatefrequency TEXT,
ADD COLUMN md_dataidentification_characterset TEXT,
ADD COLUMN specuse TEXT,
ADD COLUMN "date" TIMESTAMP,
ADD COLUMN datetype TEXT,
ADD COLUMN inpname TEXT,
ADD COLUMN ci_responsibleparty_individualname TEXT,
ADD COLUMN ci_responsibleparty_organisationname TEXT,
ADD COLUMN ci_responsibleparty_positionname TEXT,
ADD COLUMN ci_responsibleparty_voice TEXT,
ADD COLUMN ci_responsibleparty_administrativearea TEXT,
ADD COLUMN ci_responsibleparty_linkage TEXT,
ADD COLUMN ci_responsibleparty_role TEXT,
ADD COLUMN westBoundLongitude FLOAT8,
ADD COLUMN eastBoundLongitude FLOAT8,
ADD COLUMN southBoundLatitude FLOAT8,
ADD COLUMN northBoundLatitude FLOAT8,
ADD COLUMN spatialrepresentationtype TEXT,
ADD COLUMN utm_zone int4,
ADD COLUMN utm_sfctrmer FLOAT8,
ADD COLUMN utm_longcm FLOAT8,
ADD COLUMN utm_latprjo FLOAT8,
ADD COLUMN utm_feast FLOAT8,
ADD COLUMN utm_fnorth FLOAT8,
ADD COLUMN horizdn TEXT,
ADD COLUMN ellips TEXT,
ADD COLUMN semiaxis FLOAT8,
ADD COLUMN denflat FLOAT8,
ADD COLUMN "statement" TEXT,
ADD COLUMN li_processstep_description TEXT,
ADD COLUMN schemaascii TEXT,
ADD COLUMN entity_detail TEXT,
ADD COLUMN accessconstraints TEXT,
ADD COLUMN useconstraints TEXT[],
ADD COLUMN otherconstraints TEXT,
ADD COLUMN metadatastandardname TEXT,
ADD COLUMN inf_metadata_ci_responsibleparty_organisationname TEXT,
ADD COLUMN ci_responsibleparty_deliverypoint TEXT,
ADD COLUMN ci_responsibleparty_city TEXT,
ADD COLUMN ci_responsibleparty_postalcode TEXT,
ADD COLUMN ci_responsibleparty_country TEXT,
ADD COLUMN ci_responsibleparty_electronicmailaddress TEXT,
ADD COLUMN inf_metadata_ci_responsibleparty_role text;
ALTER TABLE catastro_v2.pgmetadata.dataset
ADD CONSTRAINT md_dataidentification_language CHECK (
    md_dataidentification_language IN ('ES-Español', 'EN-Inglés')
),
ADD CONSTRAINT westboundlongitude CHECK (westboundlongitude BETWEEN -180 AND 180),
ADD CONSTRAINT eastboundlongitude CHECK (eastboundlongitude BETWEEN -180 AND 180),
ADD CONSTRAINT southboundlatitude CHECK (southboundlatitude BETWEEN -90 AND 90),
ADD CONSTRAINT northboundlatitude CHECK (northboundlatitude BETWEEN -90 AND 90),
ADD CONSTRAINT utm_zone CHECK (utm_zone BETWEEN 1 AND 60),
ADD CONSTRAINT semiaxis CHECK (semiaxis > 0.0);


