services:
  backend:
    container_name: backend
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=production
    volumes:
      - ./api:/app
    networks:
      - cadastral_network

  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - backend

  frontend:
    container_name: frontend
    image: docker.io/nginx:alpine
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:5000
      - NEXT_PUBLIC_API_ENDPOINT=api
      - NEXT_PUBLIC_API_VERSION=v3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs
    networks:
      - cadastral_network
      
  vite-app:
    container_name: vite-app
    build:
      context: ./Frontend/v2
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cadastral_network

networks:
  cadastral_network:
    driver: bridge