version: '3.8'
#name: cadastral.app.container.docker
services:
  frontend:
    container_name: cadastral.react.container.docker
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend:/usr/src/Frontend
      - /usr/src/Frontend/node_modules
    ports:
      - 8080:80
    networks:
      - cadastral_network

  backend:
    container_name: cadastral.flask.container.docker
    build: 
      context: ./Backend/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./Backend:/usr/src/Backend
    ports:
      - 56733:56733

    networks:
      - cadastral_network
#[optional] If the network is not created, docker will create by itself.
networks:
  cadastral_network: {}

