version: '3.8'
#name: cadastral.app.container.docker
services:
  backend:
    container_name: cadastral.flask.container.docker
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./Backend:/usr/src/Backend
    expose:
      - 56733
    ports:
      - 56733:56733
    networks:
      - cadastral_network
  frontend:
    container_name: cadastral.react.container.docker
    build:
      context: ./Frontend/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./Frontend:/usr/src/Frontend
    expose:
      - 80
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - cadastral_network
    environment:
      - REACT_APP_API_URL=backend:56733/api/v1/

#[optional] If the network is not created, docker will create by itself.
networks:
  cadastral_network: {}
