[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
loglevel=info
user=root

[program:frontend]
command=node /app/frontend/.next/standalone/server.js
directory=/app/frontend
environment=PORT=3000,HOSTNAME="0.0.0.0"
stdout_logfile=/var/log/frontend_stdout.log
stderr_logfile=/var/log/frontend_stderr.log
autostart=true
autorestart=true
user=root

[program:backend]
command=python -m uvicorn api.src.main:app --host 0.0.0.0 --port 5000 --reload
directory=/app
environment=PYTHONPATH="/app"
stdout_logfile=/var/log/backend_stdout.log
stderr_logfile=/var/log/backend_stderr.log
autostart=true
autorestart=true
user=root

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
stdout_logfile=/var/log/nginx_stdout.log
stderr_logfile=/var/log/nginx_stderr.log
autostart=true
autorestart=true
user=root
