from typing import Any, Dict

from geoalchemy2.types import Geometry
from sqlalchemy import BigInteger, Column, Date, Float, Integer, SmallInteger, String
from sqlalchemy.orm import Mapped

from .. import config
from . import Template

db = config.db.valuaciones
float8 = Float(precision=8)


class Model(db.Model):
    __tablename__ = "catastral"

    id = Column(
        Integer,
        primary_key=True,
    )
    registro = Column(String, unique=True)
    solicitante = Column(String)
    oficio_solicitud = Column(String)
    fecha_solicitud = Column(Date)
    objetivo_avaluo = Column(String)
    proposito_avaluo = Column(String)
    inmueble_valua = Column(String)
    calle = Column(String)
    numero = Column(String)
    colonia_poblacion = Column(String)
    municipio = Column(String)
    propietario = Column(String)
    x_utm = Column(float8)
    y_utm = Column(float8)
    zona_utm = Column(SmallInteger)
    lat = Column(float8)
    long = Column(float8)
    cuenta_predial = Column(String)
    cuc = Column(String)
    clasificacion_zona = Column(String)
    agua = Column(SmallInteger)
    drenaje = Column(SmallInteger)
    energia_electrica = Column(SmallInteger)
    telefonia = Column(SmallInteger)
    tipo_pavimento = Column(String)
    alumbrado_publico = Column(SmallInteger)
    banqueta = Column(SmallInteger)
    indice_saturacion = Column(String)
    topografia = Column(String)
    myc_segun = Column(String)
    col1 = Column(String)
    med1 = Column(String)
    col2 = Column(String)
    med2 = Column(String)
    col3 = Column(String)
    med3 = Column(String)
    col4 = Column(String)
    med4 = Column(String)
    col5 = Column(String)
    med5 = Column(String)
    col6 = Column(String)
    med6 = Column(String)
    sp1_superficie = Column(float8)
    sp1_vu = Column(float8)
    sp1_factor = Column(float8)
    sp1_valor_parcial = Column(float8)
    sp2_superficie = Column(float8)
    sp2_vu = Column(float8)
    sp2_factor = Column(float8)
    sp2_valor_parcial = Column(float8)
    sp3_superficie = Column(float8)
    sp3_vu = Column(float8)
    sp3_factor = Column(float8)
    sp3_valor_parcial = Column(float8)
    sp4_superficie = Column(float8)
    sp4_vu = Column(float8)
    sp4_factor = Column(float8)
    sp4_valor_parcial = Column(float8)
    incr_esq_superficie = Column(float8)
    incr_esq_vu = Column(float8)
    incr_esq_factor = Column(float8)
    incr_esq_valor_parcial = Column(float8)
    sup_total_terreno = Column(float8)
    valor_total_terreno = Column(float8)
    uso_dominante = Column(String)
    tipo_constr_dominante = Column(String)
    muros = Column(String)
    estructura = Column(String)
    entrepisos = Column(String)
    techos = Column(String)
    pisos = Column(String)
    puertas = Column(String)
    ventanas = Column(String)
    carpinteria = Column(String)
    inst_electrica = Column(String)
    inst_sanitaria = Column(String)
    inst_especial = Column(String)
    acabado_exterior = Column(String)
    acabado_interior = Column(String)
    muebles_sanitarios = Column(String)
    cna_tipo = Column(String)
    cna_vida_util = Column(SmallInteger)
    cna_estado = Column(float8)
    cna_edad = Column(SmallInteger)
    cna_superficie = Column(float8)
    cna_vu = Column(float8)
    cna_factor = Column(float8)
    cna_valor_parcial = Column(float8)
    cnb_tipo = Column(String)
    cnb_vida_util = Column(SmallInteger)
    cnb_estado = Column(float8)
    cnb_edad = Column(SmallInteger)
    cnb_superficie = Column(float8)
    cnb_vu = Column(float8)
    cnb_factor = Column(float8)
    cnb_valor_parcial = Column(float8)
    cnc_tipo = Column(String)
    cnc_vida_util = Column(SmallInteger)
    cnc_estado = Column(float8)
    cnc_edad = Column(SmallInteger)
    cnc_superficie = Column(float8)
    cnc_vu = Column(float8)
    cnc_factor = Column(float8)
    cnc_valor_parcial = Column(float8)
    cnd_tipo = Column(String)
    cnd_vida_util = Column(SmallInteger)
    cnd_estado = Column(float8)
    cnd_edad = Column(SmallInteger)
    cnd_superficie = Column(float8)
    cnd_vu = Column(float8)
    cnd_factor = Column(float8)
    cnd_valor_parcial = Column(float8)
    sup_total_construccion = Column(float8)
    valor_total_construccion = Column(float8)
    vt_catastral = Column(float8)
    croquis_reverso = Column(SmallInteger)
    myc_segunb = Column(String)
    colb1 = Column(String)
    medb1 = Column(String)
    colb2 = Column(String)
    medb2 = Column(String)
    colb3 = Column(String)
    medb3 = Column(String)
    colb4 = Column(String)
    domicilio_geografico = Column(String)
    observaciones = Column(String)
    usuario = Column(String)
    fecha_emision = Column(Date)
    croquis = Column(String)
    foto = Column(String)
    geom = Column(
        Geometry("POINT", 32614, from_text="ST_GeomFromEWKT", name="geometry"),
        index=True,
    )
    google = Column(String)
    firmante = Column(String)
    puesto = Column(String)
    estatus = Column(Integer)
    url_docs_entrada = Column(String)
    id_entrada = Column(Integer)
    expediente = Column(String)
    zona_catastral = Column(String)
    med_col = Column(String)
    clave_avaluo = Column(BigInteger)
    asignado_por = Column(String)
    adquiriente = Column(String)
    teniente = Column(String)
    sector = Column(String)
    subsector = Column(String)
    tipo_construccion = Column(String)
    medb4 = Column(String)
    colb5 = Column(String)
    medb5 = Column(String)
    oficio_respuesta = Column(String)
    secretaria_solicitante = Column(String)
    medidas_reverso = Column(SmallInteger)
    sup_totalb = Column(float8)
    inst_esp_sup = Column(float8)
    inst_esp_vu = Column(float8)
    inst_esp_valor_parcial = Column(float8)
    cnb_muros = Column(String)
    cnb_estructura = Column(String)
    cnb_entrepisos = Column(String)
    cnb_techos = Column(String)
    cnb_pisos = Column(String)
    cnb_puertas = Column(String)
    cnb_ventanas = Column(String)
    cnb_carpinteria = Column(String)
    cnb_inst_electrica = Column(String)
    cnb_inst_sanitaria = Column(String)
    cnb_inst_especial = Column(String)
    cnb_acabado_exterior = Column(String)
    cnb_acabado_interior = Column(String)
    cnb_muebles_sanitarios = Column(String)
    cnc_muros = Column(String)
    cnc_estructura = Column(String)
    cnc_entrepisos = Column(String)
    cnc_techos = Column(String)
    cnc_pisos = Column(String)
    cnc_puertas = Column(String)
    cnc_ventanas = Column(String)
    cnc_carpinteria = Column(String)
    cnc_inst_electrica = Column(String)
    cnc_inst_sanitaria = Column(String)
    cnc_inst_especial = Column(String)
    cnc_acabado_exterior = Column(String)
    cnc_acabado_interior = Column(String)
    cnc_muebles_sanitarios = Column(String)
    cnd_muros = Column(String)
    cnd_estructura = Column(String)
    cnd_entrepisos = Column(String)
    cnd_techos = Column(String)
    cnd_pisos = Column(String)
    cnd_puertas = Column(String)
    cnd_ventanas = Column(String)
    cnd_carpinteria = Column(String)
    cnd_inst_electrica = Column(String)
    cnd_inst_sanitaria = Column(String)
    cnd_inst_especial = Column(String)
    cnd_acabado_exterior = Column(String)
    cnd_acabado_interior = Column(String)
    cnd_muebles_sanitarios = Column(String)
    colb6 = Column(String)
    medb6 = Column(String)
    avaluo = Column(String)
    cne_muros = Column(String)
    cne_estructura = Column(String)
    cne_entrepisos = Column(String)
    cne_techos = Column(String)
    cne_pisos = Column(String)
    cne_puertas = Column(String)
    cne_ventanas = Column(String)
    cne_carpinteria = Column(String)
    cne_inst_electrica = Column(String)
    cne_inst_sanitaria = Column(String)
    cne_inst_especial = Column(String)
    cne_acabado_exterior = Column(String)
    cne_acabado_interior = Column(String)
    cne_muebles_sanitarios = Column(String)
    cne_tipo = Column(String)
    cne_vida_util = Column(SmallInteger)
    cne_estado = Column(float8)
    cne_edad = Column(SmallInteger)
    cne_superficie = Column(float8)
    cne_vu = Column(float8)
    cne_factor = Column(float8)
    cne_valor_parcial = Column(float8)
    gid_domicilio = Column(BigInteger)
    num_r3 = Column(BigInteger)
    sub_num_r3 = Column(Integer, default=0)
    folio_real = Column(String)

    def __init__(self, **kwargs: Dict[str, Any]) -> None:
        for key, value in kwargs.items():
            setattr(self, key, value)


class Catastral(Template):
    def __init__(self) -> None:
        super().__init__(Model, db)

    def __enter__(self):
        return super().__enter__()

    def __exit__(self, exc_type, exc_value, traceback):
        return super().__exit__(exc_type, exc_value, traceback)
