FLASK_APP="wsgi.py"
FLASK_RUN_HOST= "0.0.0.0"
FLASK_RUN_PORT=56733
FLASK_ENV=production
DEBUG=True
SECRET_KEY= "secret"
VERSION=1
API_URL="/api/v1/"
TITLE="API DEV"
CORS="*"
CORS_ORIGIN="*"
TEMPORARY_PATH="tmp"
DATABASE_URL_DEV="postgresql://postgres:root@localhost:5432/postgres"
DATABASE_URL_TEST="postgresql://postgres:root@localhost:5432/postgres"
DATABASE_URL="postgresql://info-cat3:#jhgfye%rwA@172.31.113.151:5432/valuaciones"
