FLASK_APP="wsgi.py"
FLASK_RUN_HOST= "0.0.0.0"
FLASK_RUN_PORT=5000
FLASK_ENV="development"
DEBUG=True
SECRET_KEY= "secret"
VERSION=1
API_URL="/api/v1/"
TITLE="API DEV"
CORS="*"
CORS_ORIGIN="*"
TEMPORARY_PATH="tmp"
DATABASE_URL_DEV="postgresql://postgres:root@localhost:5432/postgres"
DATABASE_URL_TEST="postgresql://postgres:root@localhost:5432/postgres"
