/** @format */

export const section5 = {
	latres: "",
	longres: "",
	geogunit: "",
	lambertc_stdparll: "",
	lambertc_longcm: "",
	mercatort_latprjo: "",
	mercator_feast: "",
	mercator_fnorth: "",
	mercator_sfec: "",
	utm_zone: "",
	local_desc: "",
	local_geo_inf: "",
	coord_repres: "",
	ordres: "",
	absres: "",
	distance_res: "",
	bearing_res: "",
	bearing_uni: "",
	ref_bearing_dir: "",
	ref_bearing_mer: "",
	plandu: "",
	horizdn: "",
	ellips: "",
	semiaxis: "",
	altenc: "",
	altres: "",
	altunits: "",
	altdatum: "",
	depthdn: "",
	depthres: "",
	depthdu: "",
};
