new={"id",
    "uid",
    "table_name",
    "schema_name" ,
    "categories" ,
    "minimum_optimal_scale",
    "maximum_optimal_scale",
    "license",
    "confidentiality",
    "feature_count",
    "geometry_type",
    "projection_name",
    "spatial_extent" ,
    "update_date" ,
    "geom",
    "db_name" ,
    "user" ,
    "title" ,
    "purpose" ,
    "abstract" ,
    "md_dataidentification_language",
    "topiccategory" ,
    "groupcategory",
    "keyword" ,
    "presentationform",
    "ci_onlineresource_linkage" ,
    "ci_onlineresource_description" ,
    "maintenanceandupdatefrequency",
    "md_dataidentification_characterset",
    "specuse",
    "date" ,
    "datetype" ,
    "date_creation",
    "inpname",
    "ci_responsibleparty_individualname",
    "ci_responsibleparty_organisationname",
    "ci_responsibleparty_positionname",
    "ci_responsibleparty_voice" ,
    "ci_responsibleparty_administrativearea",
    "ci_responsibleparty_linkage",
    "ci_responsibleparty_role",
    "westboundlongitude" ,
    "eastboundlongitude",
    "southboundlatitude" ,
    "northboundlatitude",
    "spatialrepresentationtype",
    "utm_zone",
    "utm_sfctrmer",
    "utm_longcm" ,
    "utm_latprjo",
    "utm_feast",
    "utm_fnorth" ,
    "horizdn",
    "ellips" ,
    "semiaxis",
    "denflat",
    "level",
    "statement",
    "li_processstep_description",
    "schemaascii",
    "entity_detail",
    "accessconstraints",
    "useconstraints",
    "otherconstraints",
    "metadatastandardname",
    "inf_metadata_ci_responsibleparty_organisationname",
    "ci_responsibleparty_deliverypoint",
    "ci_responsibleparty_city",
    "ci_responsibleparty_postalcode",
    "ci_responsibleparty_country",
    "ci_responsibleparty_electronicmailaddress",
    "inf_metadata_ci_responsibleparty_role",
    "datestamp"}

old={"id",
"uid",
"table_name",
"schema_name",
"title",
"abstract",
"categories",
"keywords",
"spatial_level",
"minimum_optimal_scale",
"maximum_optimal_scale",
"publication_date",
"publication_frequency",
"license",
"confidentiality",
"feature_count",
"geometry_type",
"projection_name",
"projection_authid",
"spatial_extent",
"creation_date",
"update_date",
"geom",
"data_last_update",
"themes",
"metadata_xml",
"purpose",
"md_dataidentification_language",
"principaltopic",
"groupcategory",
"type",
"presentationform",
"ci_onlineresource_linkage",
"maintenanceandupdatefrequency",
"md_dataidentification_characterset",
"specuse",
"topiccategory",
"datestamp",
"datetype",
"date_creation",
"inpname",
"ci_responsibleparty_individualname",
"ci_responsibleparty_organisationname",
"ci_responsibleparty_positionname",
"ci_responsibleparty_linkage",
"ci_responsibleparty_role",
"westboundlongitude",
"eastboundlongitude",
"southboundlatitude",
"northboundlatitude",
"spatialrepresentationtype",
"latres",
"longres",
"geogunit",
"lambertc_stdparll",
"lambertc_longcm",
"mercatort_latprjo",
"mercator_feast",
"mercator_fnorth",
"mercator_sfec",
"coord_repres",
"ordres",
"absres",
"distance_res",
"bearing_res",
"bearing_uni",
"ref_bearing_dir",
"ref_bearing_mer",
"plandu",
"local_desc",
"local_geo_inf",
"horizdn",
"ellips",
"semiaxis",
"altenc",
"altres",
"altunits",
"altdatum",
"depthdn",
"depthres",
"depthdu",
"level",
"dq_quantitativeresult",
"dq_completeness_nameofmeasure",
"dq_logicconsistency_nameofmeasure",
"positionalaccuracy_nameofmeasure",
"temporalaccuracy_nameofmeasure",
"thematicaccuracy_nameofmeasure",
"dq_completeness_measuredescription",
"dq_logicconsistency_measuredescription",
"positionalaccuracy_measuredescription",
"temporalaccuracy_measuredescription",
"thematicaccuracy_measuredescription",
"positionalaccuracy_valueunit",
"temporalaccuracy_valueunit",
"thematicaccuracy_valueunit",
"statement",
"entity_detail",
"graphfilename",
"md_format",
"edition",
"metadatastandardname",
"metadatastandardversion",
"date",
"md_referencesystem",
"geographicelement",
"planar",
"mapprojn",
"gridcoordinatessystem",
"utm_zone",
"li_processstep",
"li_source",
}
new^old
{'utm_longcm', 'altdatum', 'user', 'ordres', 'bearing_uni', 'depthdu', 'lambertc_stdparll', 'principaltopic', 'edition', 'thematicaccuracy_valueunit', 'ci_responsibleparty_voice', 'planar', 'themes', 'utm_fnorth', 'keyword', 'bearing_res', 'thematicaccuracy_nameofmeasure', 'useconstraints', 'keywords', 'latres', 'otherconstraints', 'spatial_level', 'temporalaccuracy_measuredescription', 'inf_metadata_ci_responsibleparty_organisationname', 'inf_metadata_ci_responsibleparty_role', 'ci_onlineresource_description', 'dq_logicconsistency_nameofmeasure', 'depthdn', 'type', 'ci_responsibleparty_postalcode', 'dq_completeness_measuredescription', 'temporalaccuracy_nameofmeasure', 'longres', 'depthres', 'db_name', 'utm_sfctrmer', 'ci_responsibleparty_electronicmailaddress', 'publication_date', 'mercatort_latprjo', 'distance_res', 'data_last_update', 'local_geo_inf', 'li_processstep_description', 'mercator_sfec', 'ci_responsibleparty_deliverypoint', 'metadatastandardversion', 'thematicaccuracy_measuredescription', 'mercator_feast', 'graphfilename', 'ref_bearing_dir', 'li_processstep', 'ci_responsibleparty_administrativearea', 'creation_date', 'local_desc', 'metadata_xml', 'positionalaccuracy_valueunit', 'md_format', 'coord_repres', 'li_source', 'altenc', 'absres', 'utm_feast', 'altres', 'geographicelement', 'ref_bearing_mer', 'schemaascii', 'temporalaccuracy_valueunit', 'positionalaccuracy_nameofmeasure', 'ci_responsibleparty_city', 'plandu', 'dq_completeness_nameofmeasure', 'denflat', 'geogunit', 'altunits', 'projection_authid', 'ci_responsibleparty_country', 'utm_latprjo', 'dq_quantitativeresult', 'publication_frequency', 'dq_logicconsistency_measuredescription', 'md_referencesystem', 'gridcoordinatessystem', 'mercator_fnorth', 'mapprojn', 'accessconstraints', 'positionalaccuracy_measuredescription', 'lambertc_longcm'}
>>> new-old
{'utm_longcm', 'user', 'ci_responsibleparty_deliverypoint', 'ci_responsibleparty_voice', 'ci_responsibleparty_administrativearea', 'utm_fnorth', 'keyword', 'useconstraints', 'otherconstraints', 'utm_feast', 'inf_metadata_ci_responsibleparty_organisationname', 'inf_metadata_ci_responsibleparty_role', 'schemaascii', 'ci_onlineresource_description', 'ci_responsibleparty_city', 'denflat', 'ci_responsibleparty_postalcode', 'ci_responsibleparty_country', 'utm_latprjo', 'db_name', 'utm_sfctrmer', 'ci_responsibleparty_electronicmailaddress', 'accessconstraints', 'li_processstep_description'}
>>> old-new
{'local_geo_inf', 'altdatum', 'ordres', 'mercator_sfec', 'metadatastandardversion', 'thematicaccuracy_measuredescription', 'mercator_feast', 'bearing_uni', 'graphfilename', 'depthdu', 'lambertc_stdparll', 'principaltopic', 'edition', 'thematicaccuracy_valueunit', 'ref_bearing_dir', 'li_processstep', 'planar', 'positionalaccuracy_valueunit', 'themes', 'creation_date', 'local_desc', 'metadata_xml', 'bearing_res', 'md_format', 'thematicaccuracy_nameofmeasure', 'data_last_update', 'coord_repres', 'li_source', 'keywords', 'latres', 'spatial_level', 'temporalaccuracy_measuredescription', 'absres', 'altres', 'geographicelement', 'ref_bearing_mer', 'positionalaccuracy_measuredescription', 'temporalaccuracy_valueunit', 'positionalaccuracy_nameofmeasure', 'dq_logicconsistency_nameofmeasure', 'plandu', 'dq_completeness_nameofmeasure', 'depthdn', 'type', 'geogunit', 'mapprojn', 'dq_completeness_measuredescription', 'temporalaccuracy_nameofmeasure', 'longres', 'depthres', 'altunits', 'projection_authid', 'dq_quantitativeresult', 'publication_frequency', 'mercator_fnorth', 'dq_logicconsistency_measuredescription', 'md_referencesystem', 'gridcoordinatessystem', 'altenc', 'publication_date', 'mercatort_latprjo', 'distance_res', 'lambertc_longcm'}