/** @format */

export const records = [
	{
		id: 12345,
		fecha_captura: "2024-05-12",
		tipo_inmueble: "Casa",
		tipo_operacion: "Venta",
		captura_pantalla: "1080",
		imagen_1: "1200",
		imagen_2: "900",
		url_fuente:
			"https://www.easybroker.com/mx/home/terreno-en-venta-o-renta-comercial-con-barda-perimetral-en-guanajuato-gto-tres-estrellas",
		nombre_anunciante: "Inmobiliaria XYZ",
		telefono_anunciante: "555-1234-5678",
		x_utm: 123456.78,
		y_utm: 876543.21,
		tipo_vialidad: "Avenida",
		nombre_vialidad: "Revolución",
		numero_exterior: "123",
		numero_interior: "A",
		edificio: "Torre 1",
		entrecalles: "Entre Calle 1 y Calle 2",
		nombre_asentamiento: "Colonia Ejemplo",
		tipo_asentamiento: "Residencial",
		localidad: "Ciudad Ejemplo",
		municipio: "Ejemplo",
		estado: "Estado Ejemplo",
		regimen_propiedad: "Propiedad Privada",
		tipo_zona: "Urbana",
		uso_suelo_observado: "Habitacional",
		uso_suelo_oficial: "Residencial",
		ubicacion_manzana: "Manzana 5",
		numero_frentes: 2,
		longitud_frente: 15,
		longitud_fondo: 30,
		longitud_frente_tipo: "Metros",
		forma: "Rectangular",
		topografia: "Plana",
		superficie_terreno: 450,
		superficie_construccion: 250,
		calidad_proyecto: "Media",
		estado_conservacion: "Bueno",
		tipo_construccion: "Concreto",
		calidad_construccion: "Buena",
		edad: 10,
		niveles: 2,
		unidades_rentables: 1,
		descripcion_espacios: "3 habitaciones, 2 baños",
		agua: true,
		drenaje: true,
		energia_electrica: true,
		alumbrado_publico: true,
		banqueta: true,
		pavimento: true,
		telefonia: true,
		valor_total_mercado: 1500000,
		valor_renta: 10000,
		precio_dolar: 20,
		observaciones: "NINGUNA",
		usuario: "usuario_ejemplo",
		fh_modificacion: "2024-05-12 10:30:00",
		zona_utm: "Zona 1",
		google_maps: "http://maps.google.com?q=123456.78,876543.21",
		geom: {
			type: "Point",
			coordinates: [123456.78, 876543.21],
		},
		vtm_usd: 75000,
		tipo: "Casa Residencial",
		registro: "Registro Ejemplo",
	},
];
