from datetime import datetime
from typing import Any, Dict, Optional

from geoalchemy2 import WKBElement
from geoalchemy2.types import Geometry
from shapely.geometry import shape
from sqlalchemy import Column, Float
from sqlmodel import Field, Session, SQLModel

from ..middlewares.database import Template
from . import response_model


class Model(SQLModel, table=True):
    __tablename__ = "catastral"
    __table_args__ = {"extend_existing": True}
    id: Optional[int] = Field(default=None, primary_key=True)
    registro: str = Field(sa_column_kwargs={"unique": True})
    solicitante: str = Field(default=None)
    oficio_solicitud: str = Field(default=None)
    fecha_solicitud: datetime = Field(default=None)
    objetivo_avaluo: str = Field(default=None)
    proposito_avaluo: str = Field(default=None)
    inmueble_valua: str = Field(default=None)
    calle: str = Field(default=None)
    numero: str = Field(default=None)
    colonia_poblacion: str = Field(default=None)
    municipio: str = Field(default=None)
    propietario: str = Field(default=None)
    x_utm: float = Field(sa_column=Float(precision=70), default=None)
    y_utm: float = Field(sa_column=Float(precision=70), default=None)

    zona_utm: int = Field(default=None)
    lat: float = Field(sa_column=Float(precision=70), default=None)
    long: float = Field(sa_column=Float(precision=70), default=None)
    cuenta_predial: str = Field(default=None)
    cuc: str = Field(default=None)
    clasificacion_zona: str = Field(default=None)
    agua: bool = Field(default=None)
    drenaje: bool = Field(default=None)
    energia_electrica: bool = Field(default=None)
    telefonia: bool = Field(default=None)
    tipo_pavimento: str = Field(default=None)
    alumbrado_publico: bool = Field(default=None)
    banqueta: bool = Field(default=None)
    indice_saturacion: str = Field(default=None)
    topografia: str = Field(default=None)
    myc_segun: str = Field(default=None)
    col1: str = Field(default=None)
    med1: str = Field(default=None)
    col2: str = Field(default=None)
    med2: str = Field(default=None)
    col3: str = Field(default=None)
    med3: str = Field(default=None)
    col4: str = Field(default=None)
    med4: str = Field(default=None)
    col5: str = Field(default=None)
    med5: str = Field(default=None)
    col6: str = Field(default=None)
    med6: str = Field(default=None)
    sp1_superficie: float = Field(sa_column=Float(precision=70), default=None)
    sp1_vu: float = Field(sa_column=Float(precision=70), default=None)
    sp1_factor: float = Field(sa_column=Float(precision=70), default=None)
    sp1_valor_parcial: float = Field(sa_column=Float(precision=70), default=None)
    sp2_superficie: float = Field(sa_column=Float(precision=70), default=None)
    sp2_vu: float = Field(sa_column=Float(precision=70), default=None)
    sp2_factor: float = Field(sa_column=Float(precision=70), default=None)
    sp2_valor_parcial: float = Field(sa_column=Float(precision=70), default=None)
    sp3_superficie: float = Field(sa_column=Float(precision=70), default=None)
    sp3_vu: float = Field(sa_column=Float(precision=70), default=None)
    sp3_factor: float = Field(sa_column=Float(precision=70), default=None)
    sp3_valor_parcial: float = Field(sa_column=Float(precision=70), default=None)
    sp4_superficie: float = Field(sa_column=Float(precision=70), default=None)
    sp4_vu: float = Field(sa_column=Float(precision=70), default=None)
    sp4_factor: float = Field(sa_column=Float(precision=70), default=None)
    sp4_valor_parcial: float = Field(sa_column=Float(precision=70), default=None)
    incr_esq_superficie: float = Field(sa_column=Float(precision=70), default=None)
    incr_esq_vu: float = Field(sa_column=Float(precision=70), default=None)
    incr_esq_factor: float = Field(sa_column=Float(precision=70), default=None)
    incr_esq_valor_parcial: float = Field(sa_column=Float(precision=70), default=None)
    sup_total_terreno: float = Field(sa_column=Float(precision=70), default=None)
    valor_total_terreno: float = Field(sa_column=Float(precision=70), default=None)
    uso_dominante: str = Field(default=None)
    tipo_constr_dominante: str = Field(default=None)
    muros: str = Field(default=None)
    estructura: str = Field(default=None)
    entrepisos: str = Field(default=None)
    techos: str = Field(default=None)
    pisos: str = Field(default=None)
    puertas: str = Field(default=None)
    ventanas: str = Field(default=None)
    carpinteria: str = Field(default=None)
    inst_electrica: str = Field(default=None)
    inst_sanitaria: str = Field(default=None)
    inst_especial: str = Field(default=None)
    acabado_exterior: str = Field(default=None)
    acabado_interior: str = Field(default=None)
    muebles_sanitarios: str = Field(default=None)
    cna_tipo: str = Field(default=None)
    cna_vida_util: int = Field(default=None)
    cna_estado: float = Field(sa_column=Float(precision=70), default=None)
    cna_edad: int = Field(default=None)
    cna_superficie: float = Field(sa_column=Float(precision=70), default=None)
    cna_vu: float = Field(sa_column=Float(precision=70), default=None)
    cna_factor: float = Field(sa_column=Float(precision=70), default=None)
    cna_valor_parcial: float = Field(sa_column=Float(precision=70), default=None)
    cnb_tipo: str = Field(default=None)
    cnb_vida_util: int = Field(default=None)
    cnb_estado: float = Field(sa_column=Float(precision=70), default=None)
    cnb_edad: int = Field(default=None)
    cnb_superficie: float = Field(sa_column=Float(precision=70), default=None)
    cnb_vu: float = Field(sa_column=Float(precision=70), default=None)
    cnb_factor: float = Field(sa_column=Float(precision=70), default=None)
    cnb_valor_parcial: float = Field(sa_column=Float(precision=70), default=None)
    cnc_tipo: str = Field(default=None)
    cnc_vida_util: int = Field(default=None)
    cnc_estado: float = Field(sa_column=Float(precision=70), default=None)
    cnc_edad: int = Field(default=None)
    cnc_superficie: float = Field(sa_column=Float(precision=70), default=None)
    cnc_vu: float = Field(sa_column=Float(precision=70), default=None)
    cnc_factor: float = Field(sa_column=Float(precision=70), default=None)
    cnc_valor_parcial: float = Field(sa_column=Float(precision=70), default=None)
    cnd_tipo: str = Field(default=None)
    cnd_vida_util: int = Field(default=None)
    cnd_estado: float = Field(sa_column=Float(precision=70), default=None)
    cnd_edad: int = Field(default=None)
    cnd_superficie: float = Field(sa_column=Float(precision=70), default=None)
    cnd_vu: float = Field(sa_column=Float(precision=70), default=None)
    cnd_factor: float = Field(sa_column=Float(precision=70), default=None)
    cnd_valor_parcial: float = Field(sa_column=Float(precision=70), default=None)
    sup_total_construccion: float = Field(sa_column=Float(precision=70), default=None)
    valor_total_construccion: float = Field(sa_column=Float(precision=70), default=None)
    vt_catastral: float = Field(sa_column=Float(precision=70), default=None)
    croquis_reverso: bool = Field(default=None)
    myc_segunb: str = Field(default=None)
    colb1: str = Field(default=None)
    medb1: str = Field(default=None)
    colb2: str = Field(default=None)
    medb2: str = Field(default=None)
    colb3: str = Field(default=None)
    medb3: str = Field(default=None)
    colb4: str = Field(default=None)
    medb4: str = Field(default=None)
    colb5: str = Field(default=None)
    medb5: str = Field(default=None)
    colb6: str = Field(default=None)
    medb6: str = Field(default=None)
    domicilio_geografico: str = Field(default=None)
    observaciones: str = Field(default=None)
    usuario: str = Field(default=None)
    fecha_emision: datetime = Field(default=None)
    croquis: str = Field(default=None)
    foto: str = Field(default=None)
    geom: Any = Field(sa_column=Column(Geometry("POINT")), default=None)
    google: str = Field(default=None)
    firmante: str = Field(default=None)
    puesto: str = Field(default=None)
    estatus: int = Field(default=None)
    url_docs_entrada: str = Field(default=None)
    id_entrada: int = Field(default=None)
    expediente: str = Field(default=None)
    zona_catastral: str = Field(default=None)
    med_col: str = Field(default=None)
    clave_avaluo: int = Field(default=None)
    asignado_por: str = Field(default=None)
    adquiriente: str = Field(default=None)
    teniente: str = Field(default=None)
    sector: str = Field(default=None)
    subsector: str = Field(default=None)
    tipo_construccion: str = Field(default=None)
    oficio_respuesta: str = Field(default=None)
    secretaria_solicitante: str = Field(default=None)
    medidas_reverso: int = Field(default=None)
    sup_totalb: float = Field(sa_column=Float(precision=70), default=None)
    inst_esp_sup: float = Field(sa_column=Float(precision=70), default=None)
    inst_esp_vu: float = Field(sa_column=Float(precision=70), default=None)
    inst_esp_valor_parcial: float = Field(sa_column=Float(precision=70), default=None)
    cnb_muros: str = Field(default=None)
    cnb_estructura: str = Field(default=None)
    cnb_entrepisos: str = Field(default=None)
    cnb_techos: str = Field(default=None)
    cnb_pisos: str = Field(default=None)
    cnb_puertas: str = Field(default=None)
    cnb_ventanas: str = Field(default=None)
    cnb_carpinteria: str = Field(default=None)
    cnb_inst_electrica: str = Field(default=None)
    cnb_inst_sanitaria: str = Field(default=None)
    cnb_inst_especial: str = Field(default=None)
    cnb_acabado_exterior: str = Field(default=None)
    cnb_acabado_interior: str = Field(default=None)
    cnb_muebles_sanitarios: str = Field(default=None)
    cnc_muros: str = Field(default=None)
    cnc_estructura: str = Field(default=None)
    cnc_entrepisos: str = Field(default=None)
    cnc_techos: str = Field(default=None)
    cnc_pisos: str = Field(default=None)
    cnc_puertas: str = Field(default=None)
    cnc_ventanas: str = Field(default=None)
    cnc_carpinteria: str = Field(default=None)
    cnc_inst_electrica: str = Field(default=None)
    cnc_inst_sanitaria: str = Field(default=None)
    cnc_inst_especial: str = Field(default=None)
    cnc_acabado_exterior: str = Field(default=None)
    cnc_acabado_interior: str = Field(default=None)
    cnc_muebles_sanitarios: str = Field(default=None)
    cnd_muros: str = Field(default=None)
    cnd_estructura: str = Field(default=None)
    cnd_entrepisos: str = Field(default=None)
    cnd_techos: str = Field(default=None)
    cnd_pisos: str = Field(default=None)
    cnd_puertas: str = Field(default=None)
    cnd_ventanas: str = Field(default=None)
    cnd_carpinteria: str = Field(default=None)
    cnd_inst_electrica: str = Field(default=None)
    cnd_inst_sanitaria: str = Field(default=None)
    cnd_inst_especial: str = Field(default=None)
    cnd_acabado_exterior: str = Field(default=None)
    cnd_acabado_interior: str = Field(default=None)
    cnd_muebles_sanitarios: str = Field(default=None)
    cne_muros: str = Field(default=None)
    cne_estructura: str = Field(default=None)
    cne_entrepisos: str = Field(default=None)
    cne_techos: str = Field(default=None)
    cne_pisos: str = Field(default=None)
    cne_puertas: str = Field(default=None)
    cne_ventanas: str = Field(default=None)
    cne_carpinteria: str = Field(default=None)
    cne_inst_electrica: str = Field(default=None)
    cne_inst_sanitaria: str = Field(default=None)
    cne_inst_especial: str = Field(default=None)
    cne_acabado_exterior: str = Field(default=None)
    cne_acabado_interior: str = Field(default=None)
    cne_muebles_sanitarios: str = Field(default=None)
    cne_tipo: str = Field(default=None)
    cne_vida_util: int = Field(default=None)
    cne_estado: float = Field(sa_column=Float(precision=70), default=None)
    cne_edad: int = Field(default=None)
    cne_superficie: float = Field(sa_column=Float(precision=70), default=None)
    cne_vu: float = Field(sa_column=Float(precision=70), default=None)
    cne_factor: float = Field(sa_column=Float(precision=70), default=None)
    cne_valor_parcial: float = Field(sa_column=Float(precision=70), default=None)
    gid_domicilio: int = Field(default=None)
    num_r3: int = Field(default=None)
    sub_num_r3: int = Field(default=0)
    folio_real: str = Field(default=None)
    avaluo: str = Field(default=None)


class Catastrales(Template):
    response_model = response_model(Model)

    def __init__(self, Session: Session) -> None:
        super().__init__(Model=Model, Session=Session)
