"""Settings freeze code of the Backend"""
import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="Backend",
    version="1.0.0",
    author="Einar Jhordany Serna Valdivia",
    author_email="eserna@guanajuato.gob.mx",
    description="Package to freeze code of the Backend",
    long_description=long_description,
    long_description_content_type="text/markdown",
    packages=setuptools.find_packages(),
    include_package_data=True,
    zip_safe=False,
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
    install_requires=[
        "alabaster",
        "alembic",
        "aniso8601",
        "attrs",
        "Babel",
        "backports.zoneinfo",
        "bcrypt",
        "black",
        "certifi",
        "cffi",
        "charset-normalizer",
        "click",
        "dateparser",
        "docutils",
        "Flask",
        "Flask-Bcrypt",
        "Flask-Cors",
        "flask-marshmallow",
        "Flask-Migrate",
        "flask-restx",
        "Flask-Script",
        "Flask-SQLAlchemy",
        "Flask-Testing",
        "GeoAlchemy2",
        "greenlet",
        "id",
        "imagesize",
        "importlib-metadata",
        "importlib-resources",
        "itsdangerous",
        "Jinja2",
        "json2html",
        "jsonschema",
        "Mako",
        "MarkupSafe",
        "marshmallow",
        "marshmallow-sqlalchemy",
        "mypy-extensions",
        "numpy",
        "packagin",
        "pandas",
        "pathspec",
        "Pillow",
        "platformdirs",
        "psycopg2-binary",
        "pycparse",
        "Pygments",
        "PyJWT",
        "pyparsing",
        "PyPDF2",
        "pyrsistent",
        "python-dateutil",
        "python-dotenv",
        "pytz",
        "pytz-deprecation-shim",
        "regex2",
        "reportlab",
        "requests",
        "six",
        "snowballstemmer",
        "Sphinx",
        "sphinx-automodapi",
        "sphinx-rtd-theme",
        "sphinxcontrib-applehelp",
        "sphinxcontrib-devhelp",
        "sphinxcontrib-htmlhelp",
        "sphinxcontrib-jsmath",
        "sphinxcontrib-qthelp",
        "sphinxcontrib-serializinghtml",
        "SQLAlchemy",
        "tomli",
        "typing_extensions",
        "tzdata",
        "tzloc",
        "urllib3",
        "uui",
        "Werkzeug",
        "zipp",
    ],
)
